"""Generic script.py.mako template for Alembic migrations."""
"""Initial migration

Revision ID: d976022138ff
Revises: 
Create Date: 2026-05-06 12:25:38.473921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd976022138ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('UPLOAD', 'VIEW', 'DOWNLOAD', 'UPDATE_METADATA', 'DELETE', 'LOGIN', 'LOGOUT', 'FAILED_LOGIN', 'SEARCH', name='audit_action_enum', schema='ged'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_title', sa.String(length=500), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ged'
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False, schema='ged')
    op.create_index('ix_audit_document_id', 'audit_logs', ['document_id'], unique=False, schema='ged')
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False, schema='ged')
    op.create_index('ix_audit_user_id', 'audit_logs', ['user_id'], unique=False, schema='ged')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OPERADOR', 'GESTOR', 'ADMINISTRADOR', name='user_role_enum', schema='ged'), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='ged'
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True, schema='ged')
    op.create_index('ix_users_role', 'users', ['role'], unique=False, schema='ged')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('CONTRATO', 'PRONTUARIO', 'LAUDO', 'OFICIO', 'RECIBO', 'DECLARACAO', 'RELATORIO', 'OUTRO', name='document_type_enum', schema='ged'), nullable=False),
    sa.Column('file_format', sa.Enum('JBIG2', 'JPG', 'PDF', 'PNG', 'TIFF', name='file_format_enum', schema='ged'), nullable=False),
    sa.Column('storage_type', sa.Enum('LEGACY_NFS', 'CLOUD', name='storage_type_enum', schema='ged'), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=300), nullable=False),
    sa.Column('owner_cpf_encrypted', sa.Text(), nullable=True),
    sa.Column('owner_record_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'PENDING_DELETION', 'DELETED', name='document_status_enum', schema='ged'), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['ged.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='ged'
    )
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False, schema='ged')
    op.create_index('ix_documents_document_date', 'documents', ['document_date'], unique=False, schema='ged')
    op.create_index('ix_documents_document_type', 'documents', ['document_type'], unique=False, schema='ged')
    op.create_index('ix_documents_owner_name', 'documents', ['owner_name'], unique=False, schema='ged')
    op.create_index('ix_documents_owner_record_number', 'documents', ['owner_record_number'], unique=False, schema='ged')
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False, schema='ged')
    op.create_index('ix_documents_uploaded_by_id', 'documents', ['uploaded_by_id'], unique=False, schema='ged')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_uploaded_by_id', table_name='documents', schema='ged')
    op.drop_index('ix_documents_status', table_name='documents', schema='ged')
    op.drop_index('ix_documents_owner_record_number', table_name='documents', schema='ged')
    op.drop_index('ix_documents_owner_name', table_name='documents', schema='ged')
    op.drop_index('ix_documents_document_type', table_name='documents', schema='ged')
    op.drop_index('ix_documents_document_date', table_name='documents', schema='ged')
    op.drop_index('ix_documents_created_at', table_name='documents', schema='ged')
    op.drop_table('documents', schema='ged')
    op.drop_index('ix_users_role', table_name='users', schema='ged')
    op.drop_index('ix_users_email', table_name='users', schema='ged')
    op.drop_table('users', schema='ged')
    op.drop_index('ix_audit_user_id', table_name='audit_logs', schema='ged')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs', schema='ged')
    op.drop_index('ix_audit_document_id', table_name='audit_logs', schema='ged')
    op.drop_index('ix_audit_action', table_name='audit_logs', schema='ged')
    op.drop_table('audit_logs', schema='ged')
    # ### end Alembic commands ###
